Backend update progress api
Zeeve-App/larch pull request #72
Opened 2023-04-06 21:49 UTC by iamAbasu7

tried to fix the progress api issue #46

2023-04-06 22:35 UTC, jastisriradheshyam requested changes

2023-04-06 22:35 UTC, jastisriradheshyam commented on packages/backend/package.json
> +    "@types/node-cron": "^3.0.7",
remove this unused dependency

2023-04-06 22:35 UTC, jastisriradheshyam commented on packages/backend/package.json
> +    "node-cron": "^3.0.2",
remove this unused dependency

2023-04-06 22:35 UTC, jastisriradheshyam commented on packages/backend/src/modules/network.ts
> +// import cron from 'node-cron';
remove this unused dependency

2023-04-06 22:35 UTC, jastisriradheshyam commented on packages/backend/src/modules/network.ts
> +        await network.updateNetworkStatus(sortedResult[i].name, state);
get final state value and call this once, also remove await as this process can be done asynchronously

2023-04-06 22:35 UTC, jastisriradheshyam commented on packages/backend/src/modules/network.ts
> +    const result = await runInfo.getStatusCode(sortedResult[i].name);
do not use ExecRun class as it is not applicable to single ExecRun record, and also just get the latest one (by created at field)

2023-04-06 22:35 UTC, jastisriradheshyam commented on packages/backend/src/modules/network.ts
> +  const sortedResult = await network.getAll();
do not use Network class as it is not applicable to single network record, create a separate function for get all the network records.

2023-04-06 22:35 UTC, jastisriradheshyam commented on packages/backend/src/modules/models/network.ts
> +  async getNetworkState(network_name: string): Promise<any> {
only return network state value not the object containing network state

2023-04-06 22:35 UTC, jastisriradheshyam commented on packages/backend/src/api/larch/network/controllers.ts
> +  const result = await progressNetwork(networkName);
directly use Network object and use getNetworkState function don't have to use an abstraction function for small functionality and also check if the network exists.

2023-04-06 22:35 UTC, jastisriradheshyam commented on packages/backend/src/modules/models/network.ts
> +  async getAll(): Promise<any> {
remove it from here and create a separate function.

2023-04-06 22:35 UTC, jastisriradheshyam commented on packages/backend/src/modules/models/network.ts
> +  // }
remove commented code

2023-04-06 22:35 UTC, jastisriradheshyam commented on packages/backend/src/modules/models/network.ts
> +  // }
remove commented code

2023-04-06 22:35 UTC, jastisriradheshyam commented on packages/backend/src/modules/models/network.ts
> +      .where('name', network_name);
get network name from `this`

2023-04-06 22:35 UTC, jastisriradheshyam commented on packages/backend/src/modules/models/network.ts
> +    networkName: string,
get network name from `this`, don't get the network name separately, remove this parameter.

2023-04-06 22:35 UTC, jastisriradheshyam commented on packages/backend/src/modules/models/network.ts
> +      .where('name', networkName)
get network name from `this`

2023-04-06 22:35 UTC, jastisriradheshyam commented on packages/backend/src/modules/models/user_operation.ts
> +  }
create a separate function, don't include in Network class

2023-04-06 22:35 UTC, jastisriradheshyam commented on packages/backend/src/modules/network.ts
>  };
remove this function since, Network object will be use in controller

2023-04-07 09:06 UTC, radhe-zeeve approved these changes

2023-04-07 09:08 UTC, jastisriradheshyam approved these changes

2023-04-07 09:11 UTC, merged